tests:
  Pages should not consume too much memory:
    path: /.*
    assertions:
      - main.memory < 3M
      - main.peak_memory < 3M
  Pages should not do too many SQL queries:
    path: /.*
    assertions:
      - metrics.sql.queries.count <= 25
  Pages should be light:
    path: /.*
    assertions:
      - metrics.output.network_out < 10KB
  Pages should not do any external HTTP request:
    path: /.*
    assertions:
      - metrics.http.requests.count == 0
