version: '3.2'
services:
  cypress:
    ipc: host
    image: "cypress/included:3.4.0"
    environment:
      - CYPRESS_RECORD_KEY=${CYPRESS_RECORD_KEY}
    working_dir: /e2e
    volumes:
      - ./integration:/e2e/cypress/integration
      - ./support:/e2e/cypress/support
      - ../cypress.json/:/e2e/cypress.json
    network_mode: "host"
    command: --record
