name: Deploy
on:
  push:
    tags:
      - "*"
jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    env:
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PATH: ${{ secrets.SSH_PATH }}
    steps:
      - uses: actions/checkout@master
      - name: Build & create dist/artifact
        run: |
          npm ci
          npm run build
          composer install --no-dev --prefer-dist --no-progress --no-suggest
          bash ./bin/dist.sh
      - name: Add SSH Key
        run: |
          mkdir $HOME/.ssh
          echo "$SSH_KEY" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
      - name: Deploy to server
        run: |
          rsync -rc --exclude-from="$GITHUB_WORKSPACE/.distignore" -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no -p $SSH_PORT" "$GITHUB_WORKSPACE/dist/" $SSH_USERNAME@$SSH_HOST:$SSH_PATH
      - name: Upload Latest Version to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
          env:
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: 'us-west-1'     # optional: defaults to us-east-1
            SOURCE_DIR: 'artifact'      # optional: defaults to entire repository
            DEST_DIR: ${{ secrets.AWS_PRODUCTS_FOLDER }}/$BUILD_NAME/latest
      - name: Upload Tagged Version to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-1'     # optional: defaults to us-east-1
          SOURCE_DIR: 'artifact'      # optional: defaults to entire repository
          DEST_DIR: ${{ secrets.AWS_PRODUCTS_FOLDER }}/$BUILD_NAME/$BUILD_VERSION
