name: Deploy to QA
on:
  push:
    branches:
      - development
      - "!master"
jobs:
  deploy:
    name: Deploy to QA server
    runs-on: ubuntu-latest
    if: github.repository == 'Codeinwp/neve'
    env:
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      QA_ROOT: ${{ secrets.QA_ROOT }}
    steps:
      - uses: actions/checkout@master
      - name: Build dist
        run: |
          npm ci
          composer install --no-dev --prefer-dist --no-progress --no-suggest
          npm run dist
      - name: Authenticate
        run: |
          mkdir $HOME/.ssh
          echo "$SSH_KEY" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
      - uses: chrnorm/deployment-action@releases/v1
        name: Create deployment
        id: deployment
        with:
          token: ${{ secrets.BOT_TOKEN }}
          target_url: http://qa-neve.themeisle.com/empty-site
          environment: staging
      - name: Deploy to QA env
        run: >
          rsync -rc --exclude-from="$GITHUB_WORKSPACE/.distignore" -e "ssh -i
          $HOME/.ssh/key -o StrictHostKeyChecking=no -p $SSH_PORT"
          "$GITHUB_WORKSPACE/dist/neve/" $SSH_USERNAME@$SSH_HOST:$QA_ROOT
      - name: Rebuild Neve Reference
        run: >
          ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no
          $SSH_USERNAME@$SSH_HOST "bash ~/reset-neve-qa.sh"
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.BOT_TOKEN }}
          target_url: http://qa-neve.themeisle.com/empty-site
          state: success
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
  empty-job:
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Meep
        run: |
          echo "Nothing to do. This is a fork."
