name: E2E Tests

on: [push]
#  pull_request:
#    branches:
#      - master
env:
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

jobs:
  customizer/hfg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Customizer > HFG
        env:
          BUILD_SPEC: cypress/integration/customizer/hfg/*
        run: ./bin/run-e2e.sh

  customizer/layout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Customizer > Layout
        env:
          BUILD_SPEC: cypress/integration/customizer/layout/*
        run: ./bin/run-e2e.sh

  customizer/typography:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Customizer > Typography
        env:
          BUILD_SPEC: cypress/integration/customizer/typography/*
        run: ./bin/run-e2e.sh
   
  editor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Editor
        env:
          BUILD_SPEC: cypress/integration/editor/*
        run: ./bin/run-e2e.sh
   
   
  plugin-compat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Plugin Compatibility
        env:
          BUILD_SPEC: cypress/integration/plugins-compatibility/*
        run: ./bin/run-e2e.sh
