name: NPM Tests

on: [pull_request]

jobs:
  npm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Setup PHP version
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.1'
          extensions: simplexml
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - run: npm run build
      # WORKAROUND FOR SIZE-LIMIT
      - run: |
          GITHUB_RUN_NUMBER_TMP=GITHUB_RUN_NUMBER && export GITHUB_RUN_NUMBER=1;
          echo "$GITHUB_RUN_NUMBER"
          npm run-script size
          export GITHUB_RUN_NUMBER=GITHUB_RUN_NUMBER_TMP
          echo "$GITHUB_RUN_NUMBER"
